import os  # isort:skip
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for onebyteoftravel project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_3z*6+h-wiyejs1e=m9+wi@re6s9*pk5tn5fjbd)#mzqi1izwt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if os.getenv('SERVER_SOFTWARE', '').startswith('Google App Engine'):
    DEBUG = False



ALLOWED_HOSTS = ['*']


# Application definition





ROOT_URLCONF = 'onebyteoftravel.urls'




# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'onebyteoftravel', 'static'),
)
SITE_ID = 1


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'onebyteoftravel', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader'
            ],
        },
    },
]


MIDDLEWARE = (
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
)

#https://stackoverflow.com/questions/27093746/django-stops-working-with-runtimeerror-populate-isnt-reentrant

INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'aldryn_apphooks_config',
    'cmsplugin_filer_image',
    'parler',
    'taggit',
    'taggit_autosuggest',
    'meta',
    'sortedm2m',
    'djangocms_column',
    'djangocms_file',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'djangocms_blog',
    'aldryn_search',
    'onebyteoftravel',
)

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
)

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'public': True,
            'code': 'en',
            'hide_untranslated': False,
            'name': gettext('en'),
            'redirect_on_fallback': True,
        },
    ],
}

CMS_TEMPLATES = (
    ## Customize this
    ('djangocms_blog/post_list.html', 'PostList'),
    ('privacy.html', 'privacy'),
    ('djangocms_blog/algo_post_lists.html', 'AlgoPostList'),
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

if os.getenv('SERVER_SOFTWARE', '').startswith('Google App Engine'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/one-byte-of-travel:asia-south1:onebyteoftravel',
            'NAME': 'bytetravel',
            'PASSWORD': 'meawadh123',
            'PORT': '3306',
            'USER': 'root'
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '127.0.0.1',
            'NAME': 'bytetravel',
            'PASSWORD': 'meawadh123',
            'PORT': '3306',
            'USER': 'root'
        }
    }


MIGRATION_MODULES = {
    
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

# BLOG_POST_TEXT_CKEDITOR = {
#     'language': '{{ language }}',
#     'toolbar_HTMLField': [
#         ['Undo', 'Redo'],
#         ['cmsplugins', '-', 'ShowBlocks'],
#         ['Format', 'Styles'],
#     ],
#     'skin': 'moono-lisa',
# }

TEXT_ADDITIONAL_TAGS = ('iframe',)
TEXT_ADDITIONAL_ATTRIBUTES = ('scrolling', 'allowfullscreen', 'frameborder', 'src', 'height', 'width')

CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'allowedContent': True,
    'stylesSet': [
        {
            'name': 'H1',
            'element': 'h1',
            'attributes': {
                'class': 'page-header'
            }
        },
        {
            'name': 'H2',
            'element': 'h2',
            'attributes': {
                'class': 'page-header'
            }
        },
        {
            'name': 'H3',
            'element': 'h3',
            'attributes': {
                'class': 'page-header'
            }
        }
    ],
    # 'extraPlugins': ','.join([
    #         'uploadimage', # the upload image feature
    #         # your extra plugins here
    #         'div',
    #         'autolink',
    #         'autoembed',
    #         'embedsemantic',
    #         'autogrow',
    #         # 'devtools',
    #         'widget',
    #         'lineutils',
    #         'clipboard',
    #         'dialog',
    #         'dialogui',
    #         'elementspath'
    #     ]),
}


META_SITE_PROTOCOL = 'http'
META_USE_SITES = True
TRUNCWORDS_COUNT = 100

#Since parler 1.6 this can be skipped if the language configuration is the same as ``CMS_LANGUAGES``.
# PARLER_LANGUAGES = {
#     1: (
#         {'code': 'en',},
#         {'code': 'it',},
#         {'code': 'fr',},
#     ),
#     'default': {
#         'fallbacks': ['en'],
#     }
# }

#############################
# dajngo cms blog settings  #
#############################
BLOG_LATEST_POSTS = 5
BLOG_PAGINATION = 10
BLOG_POSTS_LIST_TRUNCWORDS_COUNT = 25

BLOG_PERMALINK_URLS = {
    'full_date': r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>\w[-\w]*)/$',
    'short_date': r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>\w[-\w]*)/$',
    'category': r'^post/(?P<category>\w[-\w]*)/(?P<slug>\w[-\w]*)/$',
    'slug': r'^post/(?P<slug>\w[-\w]*)/$',
}

BLOG_FB_APPID = "825049437700231"
BLOG_FB_PROFILE_ID = "1862489220481198"
BLOG_FB_PUBLISHER = "https://www.facebook.com/onebyteoftravel/"
BLOG_FB_AUTHOR_URL = "https://www.facebook.com/onebyteoftravel/"
BLOG_FB_AUTHOR = "https://www.facebook.com/onebyteoftravel/"

BLOG_TWITTER_SITE = "onebyteoftravel"
BLOG_TWITTER_AUTHOR = "onebyteoftravel"

BLOG_USE_ABSTRACT =  True
BLOG_USE_PLACEHOLDER = True
BLOG_USE_RELATED = True
BLOG_MULTISITE = False
BLOG_AUTHOR_DEFAULT = False
BLOG_DEFAULT_PUBLISHED = False
BLOG_ADMIN_POST_FIELDSET_FILTER = False
BLOG_AUTO_BLOG_TITLE = "One Byte Of Travel"
BLOG_SITEMAP_PRIORITY_DEFAULT = 0.5
BLOG_TAGS_PLUGIN_NAME = "Tags"
BLOG_CATEGORY_PLUGIN_NAME = "Categories"
BLOG_ARCHIVE_PLUGIN_NAME = "Archive"
BLOG_META_DESCRIPTION_LENGTH = 320
BLOG_META_TITLE_LENGTH = 70
BLOG_FEED_CACHE_TIMEOUT = 60
BLOG_FEED_INSTANT_ITEMS = 5
BLOG_FEED_LATEST_ITEMS = 5
BLOG_FEED_TAGS_ITEMS = 3
